# Generated by Django 3.2 on 2025-04-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('action_statement', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('vulnerability_level', models.CharField(max_length=100)),
                ('last_detected', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.suggestedaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerable_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_id', models.CharField(max_length=255)),
                ('threat_type', models.CharField(max_length=100)),
                ('threat_severity', models.CharField(max_length=50)),
                ('detection_time', models.DateTimeField()),
                ('suggested_actions', models.ManyToManyField(blank=True, to='api.SuggestedAction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
                ('cc_bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_detections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
